services:  
  mysql:  
    image: mysql:8.4  
    restart: always  
    container_name: mysql-nlw  
    environment:  
      - MYSQL_ROOT_PASSWORD=riso007  
    ports:  
      - '3306:3306'  # Mapeando as portas corretamente  
    networks:  
      - nlw-network  # Usando o nome correto da rede  

networks:  
  nlw-network:  # Certificando-se de que o nome da rede é consistente  
    driver: bridge